"""Screen"""
SCREEN_WIDTH = 1280
SCREEN_HEIGHT = 720

"""Sprites"""
COL_EXEMPT = 1

"""Asteroid"""
ASTEROID_SPAWN_RATE = 1

"""Player"""
SHOT_COOLDOWN = 0.2
SHIP_THRUST = 2000
SHIP_TURN = 300
DRAG = 4
MAX_SPEED = 300

"""Misc"""
OUT_OF_BOUNDS_LIMIT = 100